export default {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',

    STUDENT_SIGNUP_REQUEST:'STUDENT_SIGNUP_REQUEST',
    STUDENT_SIGNUP_SUCCESS:'STUDENT_SIGNUP_SUCCESS',

    SET_LOADING: 'SET_LOADING_AUTH',
    AUTH_ERROR: 'AUTH_ERROR',
}