export default {
    // VISIT DETAILS
    GET_VISIT_DETAILS_REQUEST:"GET_VISIT_DETAILS_REQUEST",
    GET_VISIT_DETAILS_SUCCESS:"GET_VISIT_DETAILS_SUCCESS",
    GET_VISIT_DETAILS_FAIL:"GET_VISIT_DETAILS_FAIL",
    SET_LOADING: 'SET_LOADING',
}

